version: '3'
services:
  dashboard:
    build: ./dashboard
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl localhost:8080/dashboard || exit 1"]
      start_period: 10s
      interval: 10s
      timeout: 5s
  postgres:
    build: ./postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
    # volumes:
    #   - ./postgres/data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USERNAME} -d ${DBNAME}"]
      start_period: 10s
      interval: 10s
      timeout: 5s
  pgweb:
    image: sosedoff/pgweb
    ports:
      - 8081:8081
    environment:
      PGWEB_DATABASE_URL: ${DATABASE_URL}
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl localhost:8081 || exit 1"]
      start_period: 10s
      interval: 10s
      timeout: 5s
